### ISSUE TITLE
How to set Clip Skip via Gradio GUI?

### ISSUE THREAD

**Issue by xiamubobby** [soten355/MetalDiffusion#7]
Can't find any entry for that which is normally set to 2 via CIVITAI samples but according to the console log it is always set to default 0 and having no widget to specify arbitrary values.

**Comment by soten355** [comment]
Check under advanced settings! Let me know if that worked.

**Comment by xiamubobby** [comment]
> Check under advanced settings! Let me know if that worked.

Works like a charm, thank you very much.
